name: devdar_laundry_pos_app
description: "Devdara Laundry POS - Aplikasi kasir laundry UMKM dengan fitur lengkap."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.3

  # UI Utilities
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
